esphome:
  name: "${name}"
  friendly_name: Apollo H-1
  comment: Apollo H-1
  name_add_mac_suffix: true
  platformio_options:
    board_build.flash_mode: dio

  project:
    name: "ApolloAutomation.H-1"
    version: "${version}"

  min_version: 2023.11.1
  on_boot:
    - priority: 500
      then:
        - switch.turn_on: accessory_power
        - lambda: |-
            id(deep_sleep_1).set_run_duration(id(deep_sleep_run_duration).state * 1000);
            id(deep_sleep_1).set_sleep_duration(id(deep_sleep_sleep_duration).state * 60 * 60 * 1000);
        - if:
            condition:
              or:
                - binary_sensor.is_on: ota_mode
                - switch.is_on: prevent_sleep
            then:
              - lambda: |- 
                  ESP_LOGW("Apollo", "Preventing Deep Sleep Due To OTA On Boot");
                  id(deep_sleep_1).prevent_deep_sleep(); 
    - priority: -10
      then:
        - if:
            condition:
              - lambda: "return id(runTest);"
            then:
              - lambda: "id(testScript).execute();"
  on_shutdown:
    - light.turn_off: rgb_light
    - switch.turn_off: accessory_power

safe_mode:

switch:
  - platform: template
    name: "Prevent Sleep"
    id: prevent_sleep
    icon: mdi:sleep
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: true
    entity_category: "config"

binary_sensor:
  - platform: status
    name: Online
    id: ink_ha_connected
  - platform: template
    name: "OTA Mode"
    id: ota_mode
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: true

packages:
  core: !include Core.yaml
